language: python
python:
  - "3.6"

services:
  - mysql
  - docker

env:
  global:
    - PROJECT="events-emitter"

before_install:
  - mysql -e 'CREATE DATABASE events_emitter_testing;'

install:
  - pip install -r requirements.txt

script:
  - cp events_emitter/example-settings.py events_emitter/settings.py
  - flake8
  - python manage.py migrate
  - python manage.py test

daploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: INS-4375-evaluate-rules
  