# Generated by Django 2.0.1 on 2020-02-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_emitter', '0002_eventsdependencies_event_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsdependencies',
            old_name='event_name',
            new_name='name',
        ),
    ]
