# Generated by Django 2.0.1 on 2020-03-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_emitter', '0003_auto_20200217_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('events', models.ManyToManyField(to='events_emitter.EventsDependencies')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscriptoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField()),
                ('headers', models.TextField(null=True, verbose_name='Request Headers')),
                ('event_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
