# Generated by Django 2.0.1 on 2020-03-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_emitter', '0004_users_usersubscriptoins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptoins',
            name='user_id',
            field=models.CharField(max_length=80),
        ),
    ]
